#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="${1:-$ROOT_DIR/.env.dev-auth}"
ROTATE="${DEV_AUTH_ROTATE:-0}"

if [[ -f "$OUTPUT_FILE" && "$ROTATE" != "1" ]]; then
  echo "dev-auth bootstrap skipped: $OUTPUT_FILE already exists (set DEV_AUTH_ROTATE=1 to regenerate)"
  exit 0
fi

if [[ -f "$ROOT_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT_DIR/.env"
  set +a
fi

WORKSPACE_ID_VALUE="${WORKSPACE_ID:-wk_local}"
ISSUER_VALUE="${DEV_AUTH_ISSUER:-${AUTH_ISSUER:-https://issuer.local}}"
AUDIENCE_VALUE="${DEV_AUTH_AUDIENCE:-${AUTH_AUDIENCE:-orkiva}}"
TTL_DAYS_VALUE="${DEV_AUTH_TTL_DAYS:-180}"

OUT_FILE="$OUTPUT_FILE" \
DEV_AUTH_WORKSPACE_ID="$WORKSPACE_ID_VALUE" \
DEV_AUTH_ISSUER="$ISSUER_VALUE" \
DEV_AUTH_AUDIENCE="$AUDIENCE_VALUE" \
DEV_AUTH_TTL_DAYS="$TTL_DAYS_VALUE" \
pnpm --filter @orkiva/auth exec node --input-type=module - <<'NODE'
import { generateKeyPair, exportJWK, SignJWT } from "jose";
import fs from "node:fs";

const outFile = process.env.OUT_FILE;
if (!outFile) {
  throw new Error("OUT_FILE is required");
}

const workspaceId = process.env.DEV_AUTH_WORKSPACE_ID ?? "wk_local";
const issuer = process.env.DEV_AUTH_ISSUER ?? "https://issuer.local";
const audience = process.env.DEV_AUTH_AUDIENCE ?? "orkiva";
const ttlDaysRaw = Number(process.env.DEV_AUTH_TTL_DAYS ?? "180");
const ttlDays = Number.isFinite(ttlDaysRaw) && ttlDaysRaw > 0 ? ttlDaysRaw : 180;
const now = Math.floor(Date.now() / 1000);
const exp = now + ttlDays * 24 * 60 * 60;
const keyId = "dev-local-1";

const { publicKey, privateKey } = await generateKeyPair("RS256", {
  extractable: true
});
const publicJwk = await exportJWK(publicKey);
publicJwk.kid = keyId;
publicJwk.use = "sig";
publicJwk.alg = "RS256";

const issue = async (agentId, role, sessionId) =>
  new SignJWT({
    agent_id: agentId,
    workspace_id: workspaceId,
    role,
    session_id: sessionId,
    jti: `jti_${agentId}_${now}`
  })
    .setProtectedHeader({ alg: "RS256", kid: keyId })
    .setIssuer(issuer)
    .setAudience(audience)
    .setIssuedAt(now)
    .setExpirationTime(exp)
    .sign(privateKey);

const tokens = {
  coordinator: await issue("orchestrator_agent", "coordinator", "sess_orchestrator_agent"),
  reviewer: await issue("reviewer_agent", "participant", "sess_reviewer_agent"),
  security: await issue("security_agent", "participant", "sess_security_agent"),
  executioner: await issue("executioner_agent", "participant", "sess_executioner_agent")
};
const jwksJson = JSON.stringify({ keys: [publicJwk] });

const envFile = [
  "# -----------------------------------------------------------------------------",
  "# Generated by infra/scripts/dev-auth-bootstrap.sh",
  "# Local development auth material (tokens + inline JWKS).",
  "# Regenerate by running: DEV_AUTH_ROTATE=1 pnpm run dev:auth:bootstrap",
  "# -----------------------------------------------------------------------------",
  `AUTH_ISSUER=${issuer}`,
  `AUTH_AUDIENCE=${audience}`,
  `AUTH_JWKS_JSON='${jwksJson}'`,
  `WORKER_BRIDGE_ACCESS_TOKEN=${tokens.coordinator}`,
  `DEV_ORCHESTRATOR_TOKEN=${tokens.coordinator}`,
  `DEV_REVIEWER_TOKEN=${tokens.reviewer}`,
  `DEV_SECURITY_TOKEN=${tokens.security}`,
  `DEV_EXECUTIONER_TOKEN=${tokens.executioner}`,
  ""
].join("\n");

fs.writeFileSync(outFile, envFile, { mode: 0o600 });
NODE

chmod 600 "$OUTPUT_FILE"
echo "dev-auth bootstrap complete: $OUTPUT_FILE"
